recycling-helper/config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  get 'cities/find/location', to: 'cities#by_location', as: 'city_by_location'
  get 'cities/search', to: 'cities#search', as: 'search_cities'
  get 'cities/:id/search', to: 'cities#search_items', as: 'search_items'

  get 'articles/search', to: 'articles#search', as: 'search_articles'

  resources :articles
  resources :cities, except: [:new, :create]
  resources :items, only: [:create, :update, :destroy]
  resources :bins, only: [:create, :update, :destroy]

  devise_for :admins
  devise_for :city_officials

  # The root url points to a stub page. The only role of this page is to see if a user has location
  # enabled and, if so, direct them to their cities page. Otherwise, they are sent to the real home
  # page, which is cities#index.
  root to: 'root#redirect'
end

recycling-helper/app/models/city_official.rb
class CityOfficial < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :city
  validates :first_name, :last_name, :city, presence: true
end

recycling-helper/app/views/city_officials/_form.html.erb
<%= form_for(city_official) do |f| %>
  <% if city_official.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city_official.errors.count, "error") %> prohibited this city_official from being saved:</h2>

      <ul>
      <% city_official.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

recycling-helper/app/views/city_officials/edit.html.erb
<h1>Editing City Official</h1>

<%= render 'form', city_official: @city_official %>

<%= link_to 'Show', @city_official %> |
<%= link_to 'Back', city_officials_path %>

recycling-helper/app/views/city_officials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>City Officials</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @city_officials.each do |city_official| %>
      <tr>
        <td><%= city_official.first_name %></td>
        <td><%= city_official.last_name %></td>
        <td><%= city_official.city %></td>
        <td><%= link_to 'Show', city_official %></td>
        <td><%= link_to 'Edit', edit_city_official_path(city_official) %></td>
        <td><%= link_to 'Destroy', city_official, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City Official', new_city_official_path %>

recycling-helper/app/views/city_officials/new.html.erb
<h1>New City Official</h1>

<%= render 'form', city_official: @city_official %>

<%= link_to 'Back', city_officials_path %>

recycling-helper/app/views/city_officials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @city_official.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @city_official.last_name %>
</p>

<p>
  <strong>City:</strong>
  <%= @city_official.city %>
</p>

<%= link_to 'Edit', edit_city_official_path(@city_official) %> |
<%= link_to 'Back', city_officials_path %>