recycling-helper/config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  get 'cities/find/location', to: 'cities#by_location', as: 'city_by_location'
  get 'cities/search', to: 'cities#search', as: 'search_cities'
  get 'cities/:id/search', to: 'cities#search_items', as: 'search_items'

  get 'articles/search', to: 'articles#search', as: 'search_articles'

  resources :articles
  resources :cities, except: [:new, :create]
  resources :items, only: [:create, :update, :destroy]
  resources :bins, only: [:create, :update, :destroy]

  devise_for :admins
  devise_for :city_officials

  # The root url points to a stub page. The only role of this page is to see if a user has location
  # enabled and, if so, direct them to their cities page. Otherwise, they are sent to the real home
  # page, which is cities#index.
  root to: 'root#redirect'
end

recycling-helper/app/models/article.rb
class Article < ApplicationRecord
  validates :title, :content, presence: true

  fuzzily_searchable :title, :content

  def self.fuzzy_search(query)
    return find_by_fuzzy_title(query) | find_by_fuzzy_content(query)
  end
end

recycling-helper/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :set_query, only: [:index, :search]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.order(created_at: :desc)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # GET /articles/search?query=:query
  def search
    if params[:query].nil? || params[:query] == ""
      redirect_to 'index'
      return
    end

    @query = params[:query]

    @articles = Article.fuzzy_search @query
    if @articles.empty?
      flash[:error] = "No results for \"#{@query}\"."
    else
      flash[:success] = "Found #{@articles.length} articles."
    end

    render 'index'
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    # term = Term.new(term: 'composting')
    # @article.terms << term

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    def set_query
      @query = ""
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content)
    end
end

recycling-helper/app/helpers/article_helper.rb
module ArticleHelper
end

recycling-helper/app/helpers/articles_helper.rb
module ArticlesHelper
end

recycling-helper/app/views/articles/_article.html.erb
<div class="article">

  <h3 class="panel-title article-title"><%= article.title %></h3>
  Updated <%= article.updated_at.strftime("%B %e, %Y") %>.

  <% if current_admin %>
    <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-default' %>
    <%= link_to 'Delete', article_path(article), class: 'btn btn-default', method: :delete %>
  <% end %>

  <div class="article-text">
    <%= simple_format article.content %>
  </div>

</div>

recycling-helper/app/views/articles/_form.html.erb
<%= javascript_include_tag Ckeditor.cdn_url %>

<%= form_for article do |f| %>

  <div class="form-group">
    <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.cktext_area :content, value: article.content, class: 'form-control' %>
  </div>

  <%= f.submit 'Save', class: 'btn btn-default' %>
  <%= link_to 'Cancel', article, class: 'btn btn-default' %>

<% end %>

recycling-helper/app/views/articles/_thumbnail.html.erb
<% article = thumbnail %>

<div class="panel panel-default article clickable" onclick="location.href='<%= article_path(article) %>'" >
  <div class="panel-heading">
    <h3 class="panel-title article-title"><%= article.title %></h3>
  </div>
  <div class="panel-body article-text">
    <% if article.content.length > 500 %>
      <%= simple_format article.content[0..500] + '... <a>(more)</a>' %>
    <% else %>
      <%= simple_format article.content %>
    <% end %>
  </div>
</div>

recycling-helper/app/views/articles/create.html.erb
<h1>Create a New Article</h1>
<p>Find me in app/views/articles/create.html.erb</p>

<% @articles.each do |x| %>
	<%= x.name %>
<% end %> 

recycling-helper/app/views/articles/edit.html.erb
<%= render 'form', article: @article %>

recycling-helper/app/views/articles/index.html.erb
<% if current_admin %>
  <%= link_to 'New Article', new_article_path, class: 'btn btn-default' %>
<% end %>

<div style="margin: 15px;">
  <%= form_tag search_articles_path, :method => "get", class: 'form-inline' do %>
    <%= text_field_tag :query, @query, {placeholder: "Search for an article...", class: 'form-control'} %>
    <%= submit_tag "Search", class: 'btn btn-default btn-primary' %>
  <% end %>
</div>

<%= render partial: 'thumbnail', collection: @articles %>

recycling-helper/app/views/articles/new.html.erb
<%= render 'form', article: @article %>

recycling-helper/app/views/articles/show.html.erb
<%= render @article %>