recycling-helper/config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  get 'cities/find/location', to: 'cities#by_location', as: 'city_by_location'
  get 'cities/search', to: 'cities#search', as: 'search_cities'
  get 'cities/:id/search', to: 'cities#search_items', as: 'search_items'

  get 'articles/search', to: 'articles#search', as: 'search_articles'

  resources :articles
  resources :cities, except: [:new, :create]
  resources :items, only: [:create, :update, :destroy]
  resources :bins, only: [:create, :update, :destroy]

  devise_for :admins
  devise_for :city_officials

  # The root url points to a stub page. The only role of this page is to see if a user has location
  # enabled and, if so, direct them to their cities page. Otherwise, they are sent to the real home
  # page, which is cities#index.
  root to: 'root#redirect'
end

recycling-helper/app/models/bin.rb
class Bin < ApplicationRecord
  validates :name, :city, :red, :green, :blue, :alpha, presence: true
  validates :red, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 255 },
    if: 'red.present?'
  validates :green, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 255 },
    if: 'green.present?'
  validates :blue, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 255 },
    if: 'blue.present?'
  validates :alpha, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 1 },
    if: 'alpha.present?'

  belongs_to :city
  has_and_belongs_to_many :items, ->{ order :name }
  has_many :categories, -> { distinct }, through: :items

  # Add an item to this bin, reusing an existing item if possible. Returns the added item. If the
  # item exists but does not match category, then an exception will be raised and the database will
  # not be touched.
  def add_item!(name, category, image)
    begin
      result = Item.create(name: name, category: category, image: image)
      items << result
    rescue ActiveRecord::RecordNotUnique
      # This item already exists in the database
      existing = Item.find_by name: name

      # Verify that this is really the item we think it is: it should have the correct category
      if existing.category == category
        result = existing
        items << result
      else
        # Something has gone wrong
        raise Errors::InvalidCategoryForItem,
          "category for \"#{name}\" should be \"#{existing.category.name}\""
      end
    end

    result
  end

  # Add a series of items to this bin, reusing existing items where possible. Items must respond to
  # each, and each item should be a hash containing keys :name and :category.
  def add_items!(items)
    items.map do |item|
      add_item! item[:name], item[:category], item[:image]
    end
  end

  def color
    { red: red, green: green, blue: blue, alpha: alpha }
  end

  def css_color
    "rgba(#{red}, #{green}, #{blue}, #{alpha})"
  end

end

recycling-helper/app/controllers/bins_controller.rb
class BinsController < ApplicationController
  before_action :set_bin, only: [:update, :destroy]

  # POST /bins
  # POST /bins.json
  def create
    @bin = Bin.new(bin_params)

    respond_to do |format|
      if save_bin(@bin)
        format.html { redirect_to @bin, notice: 'Bin was successfully created.' }
        format.json { render json: { ok: true, bin: @bin } }
      else
        format.html { render :new }
        format.json {
          bin = Bin.find_by(id: @bin.id) || {}
          render json:
          { ok: false, errors: @bin.errors.full_messages, bin: bin }
        }
      end
    end
  end

  # PATCH/PUT /bins/1
  # PATCH/PUT /bins/1.json
  def update
    @bin.assign_attributes bin_params

    respond_to do |format|
      if save_bin @bin
        format.html { redirect_to @bin, notice: 'Bin was successfully updated.' }
        format.json { render json: { ok: true, bin: @bin } }
      else
        Rails.logger.error "Failed to update bin #{params[:id]}"
        format.html { render :edit }
        format.json { render json: {
          # Respond with the current state of the bin in the database
          ok: false, errors: @bin.errors.full_messages, bin: Bin.find_by(id: params[:id]) }
        }
      end
    end
  end

  # DELETE /bins/1
  # DELETE /bins/1.json
  def destroy
    @bin.destroy
    respond_to do |format|
      format.html { redirect_to bins_url, notice: 'Bin was successfully destroyed.' }
      format.json { render json: { ok: true } }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bin
      @bin = Bin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bin_params
      params.require(:bin).permit(:name, :city_id, :red, :green, :blue, :alpha)
    end

    # Create a new bin and return a boolean indicating success
    def save_bin(bin)
      begin
        bin.save
      rescue ActiveRecord::RecordNotUnique
        bin.errors.add :base, :not_unique, message:
          "A bin with the name \"#{bin.name}\" already exists for this city."
      end

      return bin.errors.empty?
    end

end

recycling-helper/app/helpers/bins_helper.rb
module BinsHelper
end

recycling-helper/app/views/bins/_bin.html.erb
<%= render partial: 'items/collection', locals: {
  id: bin.id,
  name: bin.name.titleize,
  items: bin.items.order(:name),
  color: bin.color
} %>

recycling-helper/app/views/bins/_form.html.erb
<!--
This file contains a template detailing the structure used to display a bin in the city editor.
Because bins are created, deleted, and edited dynamically in the browser, we do not use this
template to render any specific bins on the server side. Rather, this is a generic outline with
holes which will be filled in clientside. A somewhat peculiar necessity that arises out of this is
that we use name attributes like we would usually use ids, since this template will be duplicated
many times and thus the ids would not be unique. Whenever a new bin is instantiated, each element
with a name attribute will receive an id of the form bin#{bin.id}_#{name}.
-->

<div class="bin" id="bin_template">
  <div class="heading">
    <form class="inline" name="form">
      <div class="input-group">
        <input type="text" class="form-control" name="name_input"/>
        <span class="input-group-addon">
          <a class="btn btn-default" name="color_input"></a>
        </span>
      </div>
    </form>

    <span name="title_bar">
      <button type="button" name="edit" class="icon left-align">
        <span class="glyphicon glyphicon-pencil"></span>
      </button>
      <h3 class="title inline" name="title"></h3>
      <button type="button" name="delete" class="close">&times;</button>
    </span>
  </div>


  <ul class="body scrollable-list" name="items">
  </ul>

  <div class="footer">
    <button type="button" class="btn btn-default" name="remove_items">Remove selected</button>
  </div>
</div>

recycling-helper/app/views/bins/create.html.erb
<h1>Bins#create</h1>
<p>Find me in app/views/bins/create.html.erb</p>


<h1>A Greeting for You!</h1>
<p><%= @message %></p>

recycling-helper/app/views/bins/edit.html.erb
<h1>Editing Bin</h1>

<%= render 'form', bin: @bin %>

<%= link_to 'Show', @bin %> |
<%= link_to 'Back', bins_path %>

recycling-helper/app/views/bins/index.html.erb
<<<<<<< HEAD
<p id="notice"><%= notice %></p>

<style>

h1 { 
  text-align: center;
  font-size:20;
  color: green;
}

body {
  background-color:black;
}

table{
  color:green;
  text-align: center;
  width: 100%;
  height: 300px;
  vertical-align: middle;
}

td{

  height:100px;
}
</style>

<% binLocation= @bins.first.city.name %>

<h1>YOU ARE IN <%= @bins.first.city.name %></h1>

<br>
<br>
<br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bins.each do |bin| %>
      <tr>
        <td><%= bin.name %></td>
        <td><%= bin.city.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bin', new_bin_path %>
=======
<h1>Bins#index</h1>
<p>Find me in app/views/bins/index.html.erb</p>

<% @bins.each do |x| %>
	<h3><%= x.name %></h3>
	<% x.items.each do |y| %>
		<p><%= y.name %></p>
	<% end %>


<% end %>
>>>>>>> Add files for bin and city controllers

recycling-helper/app/views/bins/new.html.erb
<h1>New Bin</h1>

<%= render 'form', bin: @bin %>

<%= link_to 'Back', bins_path %>

recycling-helper/app/views/bins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bin.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @bin.city %>
</p>

<%= link_to 'Edit', edit_bin_path(@bin) %> |
<%= link_to 'Back', bins_path %>