recycling-helper/config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  get 'cities/find/location', to: 'cities#by_location', as: 'city_by_location'
  get 'cities/search', to: 'cities#search', as: 'search_cities'
  get 'cities/:id/search', to: 'cities#search_items', as: 'search_items'

  get 'articles/search', to: 'articles#search', as: 'search_articles'

  resources :articles
  resources :cities, except: [:new, :create]
  resources :items, only: [:create, :update, :destroy]
  resources :bins, only: [:create, :update, :destroy]

  devise_for :admins
  devise_for :city_officials

  # The root url points to a stub page. The only role of this page is to see if a user has location
  # enabled and, if so, direct them to their cities page. Otherwise, they are sent to the real home
  # page, which is cities#index.
  root to: 'root#redirect'
end

recycling-helper/app/models/city.rb
require_dependency 'validators/state_validator.rb'
class City < ApplicationRecord
  validates :name, :state, :location_id, presence: true
  validates :state, state: true, if: 'state.present?'
  validates :website_url, format: { with: URI.regexp, message: 'is not a valid URL' },
    if: 'website_url.present?'
  validates :city_phone, presence: true

  has_many :zip_codes
  has_many :bins, inverse_of: :city
  has_many :items, through: :bins
  has_many :categories, -> { distinct }, through: :items
  has_many :officials, class_name: 'CityOfficial', inverse_of: :city
end

recycling-helper/app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
    @city = City.find(params[:id])
    @categories = Category.all
    @bins = @city.bins
  end

  # GET /cities/1/edit
  def edit
  end

  def itemLookupResult
    render
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render json: { ok: true, city: @city } }
      else
        format.html { render :edit }
        format.json { render json: { ok: false, errors: @city.errors.full_messages } }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :state, :website_url, :city_phone)
    end


end

recycling-helper/app/helpers/cities_helper.rb
module CitiesHelper
end

recycling-helper/app/views/cities/_form.html.erb
<script type="text/javascript">
  $(document).ready(function() {

    // Initialize the state of the world
    init_bins(JSON.parse('<%= raw @city.bins.order(:created_at).to_json(include: :items) %>'))
    init_items(
      JSON.parse(
        '<%= raw Category.order(:name).map { |category|
          [category.id, category.items]
        }.to_h.to_json %>'
      )
    )

    <% if @city.website_url.blank? %>
      show_url_form(<%= @city.id %>)
    <% else %>
      show_url(<%= @city.id %>, '<%= @city.website_url %>')
    <% end %>

    <% if @city.city_phone.blank? %>
    <% else %>
      show_url(<%= @city.id %>, '<%= @city.website_url %>')
    <% end %>

    $('.modal').on('shown.bs.modal', function() {
      // Autofocus input when popup is shown
      $(this).find('[autofocus]').focus();

      // Autoset category if one of the categories is selected
      $(this).find('[name=category_id]').val(active_category() || '')
    });

    // Reset popup dialog when closed
    $('#new-item').on('hidden.bs.modal', function() {
      $('#new-item-errors').empty()
      $('#new-item').find('[name=name]').val('')
      $('#new-item').find('[name=category_id]').val('')
    })

    // Do not redirect on new item submission
    $('#new-item-form').submit(function(e) {
      e.preventDefault()
      save_new_item()
    })
  })

</script>

<h1><%= @city.name %>, <%= @city.state %></h1>

<div id="url"></div>

<hr>

<!-- New item popup -->
<div class="modal fade" id="new-item" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">New Item</h4>
      </div>
      <div class="modal-body">
        <div id="new-item-errors">
          <!-- Filled in dynamically -->
        </div>

        <form id="new-item-form">
          <div class="form-group">
            <input type="text" placeholder="Name" class="form-control" name="name" autofocus>
          </div>
          <div class="form-group">
            <%= collection_select :item, :category_id, Category.all, :id, :name,
              {prompt: 'Choose a category'},
              {class: 'form-control', name: 'category_id'} %>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary" onclick="$('#new-item-form').submit()">Save</button>
      </div>
    </div>
  </div>
</div>

<div class="container">

  <div class="panel panel-default">

    <div class="panel-heading">
      <div class="row no-gutters">
        <div class="col-xs-6">
          <h3 class="panel-title">Categories</h3>
        </div>
        <div class="col-xs-6">
          <h3 class="panel-title">Items</h3>
        </div>
      </div>
    </div>

    <% def set_height
        list_height = (Category.count + 2) * 35 + 2
        "max-height: #{list_height}px; min-height: #{list_height}px;"
      end
    %>

    <% def set_width
        list_width = 250
        "max-width: #{list_width}px; min-width: #{list_width}px;"
      end
    %>

    <div class="row no-gutters">
      <div class="col-xs-6" style="padding-right: 0;">

        <ul id="categories" class="scrollable-list" style="<%= set_height %>">
          <li id="all_categories" onclick="display_all_items()" class="list-group-item btn btn-default">
            All Items
          </li>

          <% Category.all.each do |category| %>
            <li id="category<%= category.id %>" onclick="filter_by_category(<%= category.id %>)" class="list-group-item btn btn-default">
              <%= category.name %>
            </li>
          <% end %>
        </ul>

      </div> <!-- col -->

      <div class="col-xs-6" style="padding-left: 0;">
        <ul id="items" class="scrollable-list" style="<%= set_height %>">
          <!-- Filled in by JS -->
        </ul>

        <div class="btn-group" >
          <button type="button" class="btn btn-default" onclick="select_all(true)">Select All</button>
          <button type="button" class="btn btn-default" onclick="select_all(false)">Unselect All</button>
          <button type="button" class="btn btn-default" data-keyboard="true"data-toggle="modal" data-target="#new-item">
            <span class = "glyphicon glyphicon-plus"> </span>
            New item
          </button>
        </div>

        <div class="dropdown">
          <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Add to bin</span> <span class="caret"></span></button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" id="bin_dropdown">
          </div>
        </div>
      </div> <!-- col -->
    </div> <!-- row -->

  </div> <!-- panel -->
</div>

<div id="bins">
  <!-- Filled in dynamically -->

  <!-- New bin -->
  <div class="bin">
    <div class="heading">
      <form id="new-bin-form">
        <div class="input-group">
          <input type="text" class="form-control" name="name_input" placeholder="Add a new bin"/>
          <span class="input-group-addon">
            <a class="btn btn-default" name="color_input"></a>
          </span>
        </div>
        <input type="hidden" name="city_input" value="<%= @city.id %>"/>
      </form>
    </div>
    <div class="body concentric">
      <div class="clickable well inset" onclick="click_new_bin()">
        <span class = "glyphicon glyphicon-plus"></span>
      </div>
    </div>
    <div class="footer">
    </div>
  </div>
</div>

<div style="visibility: hidden;">
  <%= render 'bins/form' %>
</div>

recycling-helper/app/views/cities/edit.html.erb
<%= render 'form', city: @city %>
<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

recycling-helper/app/views/cities/index.html.erb
<%= stylesheet_link_tag "cities" %>

<script type="text/javascript">
  <% unless @cities.empty? %>
    // Scroll down to search results
    $(document).ready(function() {
      scroll_to("#cities")
    })
  <% end %>
</script>

<div class="full-window centerable">
  <div class="rh-panel">

    <div class="centered">
      <h3>Welcome to the Recycling Helper</h3>
      <hr>

      <%= form_tag search_cities_path, method: :get, class: "" do %>

        <div class="form-group">
          <%= text_field_tag :query, nil, {
            class: 'form-control',
            placeholder: 'Enter your zip code or city...',
            value: @query,
            tabindex: 1,
            autofocus: true
          } %>
        </div>

        <%= submit_tag 'Go', class: 'btn btn-default btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

<ul id="cities" class="list-group">
  <% @cities.sort_by!{ |city| city.name } %>
  <% @cities.each do |city| %>
    <% if city.zip_codes.length > 1 %>
      <li class="list-group-item btn btn-default" onclick="window.location.href = '<%= city_path city %>'">
        <%= "#{city.name}, #{city.state} #{city.zip_codes[0].name} - #{city.zip_codes[1].name}" %>
      </li>
    <% else %>
      <li class="button" onclick="window.location.href = '<%= city_path city %>'">
        <%= "#{city.name}, #{city.state} #{city.zip_codes[0].name}" %>
      </li>
    <% end %>
  <% end %>
</ul>

recycling-helper/app/views/cities/itemLookupResult.erb
<html>
<%= abcd = 'a' %>
<p> abcd </p>
</html>

recycling-helper/app/views/cities/show.html.erb
<% content_for :js do %>
  <script type="text/javascript">
    $(document).ready(function() {
      init_smooth_scrolling()

      <% if @items %>
        // Scroll to search results
        scroll_to("#search_results")

        // Link search results to the proper bin
        <% @items.each do |item| %>
          $item = $("#search_results [name=\"item<%= item.id %>\"]")
          $item.css('cursor', 'pointer')
          $item.click(function() {
            $bin = $("#bin<%= item.bins.find_by(city: @city).id %>")
            scroll_to($bin)
            $page = $bin.find('[name=\"categories\"]').children().has("[name=\"item<%= item.id %>\"]")
            select_page($bin, $page)
          })
        <% end %>
      <% end %>
    })
  </script>
<% end %>

<nav id="bin_links">
  <a class="to-top bin-link"><%= @city.name %>, <%= @city.state %></a>

	<% @city.bins.each do |bin| %>
		<a href="#bin<%= bin.id%>" class="bin-link"><%= bin.name.titleize %></a>
	<% end %>
</nav>

<div class="full-window centerable">
  <div class="rh-panel">
    <div class="centered">
      <h1><%= @city.name %>, <%= @city.state %></h1>
      <h3><%= @city.zip_codes.first.name %></h3>

      <% if @city.website_url.present? %>
        <a href="<%= @city.website_url %>"><%= @city.website_url %></a><br>
      <% end %>
      <% if @city.phone_number.present? || @city.email.present? %>
        Contact:
        <% if @city.phone_number.present? && @city.email.present? %>
          <%= @city.phone_number %> or <%= @city.email %>
        <% elsif @city.phone_number.present? %>
          <%= @city.phone_number %>
        <% else %>
          <%= @city.email %>
        <% end %>
      <% end %>

      <hr>

      <!-- Search bar-->
      <%= form_tag search_items_path(@city), :method => "get", id: 'search_items', class: 'form-inline', onsubmit: 'search_items()' do %>
        <%= text_field_tag :query, @query, {placeholder: "Search for an item...", class: 'form-control'} %>
        <%= submit_tag "Search", class: 'btn btn-default btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

<% if @items %>
  <div id="search_results">
    <%= render partial: 'items/collection', locals: {
      items: @items,
      id: 'search_result_items',
      name: "Found #{@items.length} items matching \"#{@query}\"",
      color: { red: 200, green: 255, blue: 200, alpha: 0.5 }
    } %>
  </div>
<% end %>

<div id="bins">
  <%= render partial: 'bins/bin', collection: @city.bins, locals: {city: @city} %>
</div>

<footer>
<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>
</footer>